config/routes.rb
Worldgenerator::Application.routes.draw do
  match "map" => "zones#map" , :as => "map", :via => "GET"
  resources :zones
  match "zones/:x/:y/:z" => "zones#index" , :as => "zone_select", :via => "GET"
  

  resources :climates
  match "climates/:id/clone" => "climates#clone" , :as => "clone_climate", :via => "PUT"

   root :to => 'zones#index'

end

app/models/climate.rb
class Climate < ActiveRecord::Base
  attr_accessible :color, :description, :interacts, :name, :overlaps, :probability, :radius, :scale, :x, :y, :z, :default
end

app/models/zone.rb
class Zone < ActiveRecord::Base
  attr_accessible :visited, :x, :y, :z
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/climates_controller.rb
class ClimatesController < ApplicationController
  # GET /climates
  # GET /climates.json
  def index
    @climates = Climate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @climates }
    end
  end

  # GET /climates/1
  # GET /climates/1.json
  def show
    @climate = Climate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @climate }
    end
  end

  # GET /climates/new
  # GET /climates/new.json
  def new
    @climate = Climate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @climate }
    end
  end

  # GET /climates/1/edit
  def edit
    @climate = Climate.find(params[:id])
  end

  # POST /climates
  # POST /climates.json
  def create
    @climate = Climate.new(params[:climate])

    respond_to do |format|
      if @climate.save
        format.html { redirect_to @climate, notice: 'Climate was successfully created.' }
        format.json { render json: @climate, status: :created, location: @climate }
      else
        format.html { render action: "new" }
        format.json { render json: @climate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /climates/1
  # PUT /climates/1.json
  def update
    @climate = Climate.find(params[:id])

    respond_to do |format|
      if @climate.update_attributes(params[:climate])
        format.html { redirect_to climates_path, notice: 'Climate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @climate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /climates/1
  # PUT /climates/1.json
  def clone
    @climate = Climate.find(params[:id])
    @climate_clone=@climate.dup
    @climate_clone.name+=" (clone)"
    respond_to do |format|
       if @climate_clone.save()
        @climate=@climate_clone
         format.html { redirect_to climates_url, notice: 'Climate was successfully cloned.' }
         format.json { head :no_content }
       else
      #   format.html { redirect_to climate, notice: :unprocessable_entity }
      #   format.json { render json: @climate.errors, status: :unprocessable_entity }
       end
    end
  end

  # DELETE /climates/1
  # DELETE /climates/1.json
  def destroy
    @climate = Climate.find(params[:id])
    @climate.destroy

    respond_to do |format|
      format.html { redirect_to climates_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  # GET /zones
  # GET /zones.json

  def map

    @climates = Climate.all
    #check boundaries
    bound_x=Zone.maximum(:x)-Zone.minimum(:x)
    bound_y=Zone.maximum(:y)-Zone.minimum(:y)

    @zones = Zone.all

    @boundaries = []
    @boundaries = {:x => bound_x, :y => bound_y}

    respond_to do |format|
      format.html # map.html.erb
      format.json { render json: @zones }
    end
  end

  def index
    @x = params[:x].blank? ? 0 : params[:x].to_i
    @y = params[:y].blank? ? 0 : params[:y].to_i
    @z = params[:z].blank? ? 0 : params[:z].to_i

    #create the zone if doesn't exist
    @zone = Zone.find_or_create_by_x_and_y_and_z(@x, @y, @z)
    @zone.visited=true
    @zone.save


    #get the existing climates
    @climates = []
    climates=Climate.all()
    climates.each do |climate|
      climate[:distance] = Math::sqrt((climate.x - @zone.x)**2 + (climate.y - @zone.y)**2)
    end
    climates.keep_if {|v| v[:radius] >= v[:distance] || v[:default]}
    @climates=climates

    # #create the climate if doesn't exist

    if climates.size <= 2

      #   #check boundaries
      bound_x=Range.new(Zone.minimum("x").to_i, Zone.maximum("x").to_i)
      bound_y=Range.new(Zone.minimum("y").to_i, Zone.maximum("y").to_i)
      bound_z=Range.new(Zone.minimum("z").to_i, Zone.maximum("z").to_i)

      #     #check directions
      dir_x = @x.to_i>=0 ? 1 : -1
      dir_y = @y.to_i>=0 ? 1 : -1
      dir_z = @z.to_i>=0 ? 1 : -1

      @bound = "s"
      random_value = ((Random.rand(bound_x) + Random.rand(bound_y) + Random.rand(bound_z))/3).to_i.abs

        new_climate=Climate.new()
        new_climate.name = rand(36**16).to_s(36)
        new_climate.x = @x+dir_x*Random.rand(bound_x).to_i.abs
        new_climate.y = @y+dir_y*Random.rand(bound_y).to_i.abs
        new_climate.z = @z+dir_z*Random.rand(bound_z).to_i.abs
        new_climate.color = "##{Random.rand(255).to_s(16)}#{Random.rand(255).to_s(16)}#{Random.rand(255).to_s(16)}"
        new_climate.radius = Random.rand(random_value)
        new_climate.scale = Random.rand(100)/10
                      new_climate.save()
                      end



                      climates.sort_by { |h| h[:distance] }
                      @climates = climates

                      respond_to do |format|
                        format.html # show.html.erb
                        format.json { render json: @zone }
                      end
                      end

                      # GET /zones/1
                      # GET /zones/1.json
                      def show
                        @zone = Zone.find(params[:id])
                        respond_to do |format|
                          format.html # show.html.erb
                          format.json { render json: @zone }
                        end
                      end

                      # GET /zones/new
                      # GET /zones/new.json
                      def new
                        @zone = Zone.new

                        respond_to do |format|
                          format.html # new.html.erb
                          format.json { render json: @zone }
                        end
                      end

                      # GET /zones/1/edit
                      def edit
                        @zone = Zone.find(params[:id])
                      end

                      # POST /zones
                      # POST /zones.json
                      def create
                        @zone = Zone.new(params[:zone])

                        respond_to do |format|
                          if @zone.save
                            format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
                            format.json { render json: @zone, status: :created, location: @zone }
                          else
                            format.html { render action: "new" }
                            format.json { render json: @zone.errors, status: :unprocessable_entity }
                          end
                        end
                      end

                      # PUT /zones/1
                      # PUT /zones/1.json
                      def update
                        @zone = Zone.find(params[:id])

                        respond_to do |format|
                          if @zone.update_attributes(params[:zone])
                            format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
                            format.json { head :no_content }
                          else
                            format.html { render action: "edit" }
                            format.json { render json: @zone.errors, status: :unprocessable_entity }
                          end
                        end
                      end

                      # DELETE /zones/1
                      # DELETE /zones/1.json
                      def destroy
                        @zone = Zone.find(params[:id])
                        @zone.destroy

                        respond_to do |format|
                          format.html { redirect_to map_url }
                          format.json { head :no_content }
                        end
                      end
                      end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/climates_helper.rb
module ClimatesHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/climates/_form.html.erb
<%= form_for(@climate) do |f| %>
  <% if @climate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@climate.errors.count, "error") %> prohibited this climate from being saved:</h2>

      <ul>
      <% @climate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :probability %><br />
    <%= f.text_field :probability %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_area :color %>
  </div>
  <div class="field">
    <%= f.label :radius %><br />
    <%= f.text_field :radius %>
  </div>
  <div class="field">
    <%= f.label :scale %><br />
    <%= f.text_field :scale %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :interacts %><br />
    <%= f.check_box :interacts %>
  </div>
  <div class="field">
    <%= f.label :overlaps %><br />
    <%= f.check_box :overlaps %>
  </div>
  <div class="field">
    <%= f.label :x %><br />
    <%= f.text_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.text_field :y %>
  </div>
  <div class="field">
    <%= f.label :z %><br />
    <%= f.text_field :z %>
  </div>
  <div class="field">
    <%= f.label :default %><br />
    <%= f.check_box :default %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/climates/edit.html.erb
<h1>Editing climate</h1>

<%= render 'form' %>

<%= link_to 'Show', @climate %> |
<%= link_to 'Back', climates_path %>

app/views/climates/index.html.erb
<h1>Listing climates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Probability</th>
    <th>Color</th>
    <th>Radius</th>
    <th>Scale</th>
    <th>Description</th>
    <th>Interacts</th>
    <th>Overlaps</th>
    <th>X</th>
    <th>Y</th>
    <th>Z</th>
    <th>Default</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @climates.each do |climate| %>
  <tr>
    <td><%= climate.name %></td>
    <td><%= climate.probability %></td>
    <td><%= climate.color %></td>
    <td><%= climate.radius %></td>
    <td><%= climate.scale %></td>
    <td><%= climate.description %></td>
    <td><%= climate.interacts %></td>
    <td><%= climate.overlaps %></td>
    <td><%= climate.x %></td>
    <td><%= climate.y %></td>
    <td><%= climate.z %></td>
    <td><%= climate.default %></td>
    <td><%= link_to 'Show', climate %></td>
    <td><%= link_to 'Clone', clone_climate_path(climate), method: :put %></td>
    <td><%= link_to 'Edit', edit_climate_path(climate) %></td>
    <td><%= link_to 'Destroy', climate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Climate', new_climate_path %>

app/views/climates/new.html.erb
<h1>New climate</h1>

<%= render 'form' %>

<%= link_to 'Back', climates_path %>

app/views/climates/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @climate.name %>
</p>

<p>
  <b>Probability:</b>
  <%= @climate.probability %>
</p>

<p>
  <b>Color:</b>
  <%= @climate.color %>
</p>

<p>
  <b>Radius:</b>
  <%= @climate.radius %>
</p>

<p>
  <b>Scale:</b>
  <%= @climate.scale %>
</p>

<p>
  <b>Description:</b>
  <%= @climate.description %>
</p>

<p>
  <b>Interacts:</b>
  <%= @climate.interacts %>
</p>

<p>
  <b>Overlaps:</b>
  <%= @climate.overlaps %>
</p>

<p>
  <b>X:</b>
  <%= @climate.x %>
</p>

<p>
  <b>Y:</b>
  <%= @climate.y %>
</p>

<p>
  <b>Z:</b>
  <%= @climate.z %>
</p>
<p>
  <b>Default:</b>
  <%= @climate.default %>
</p>


<%= link_to 'Edit', edit_climate_path(@climate) %> |
<%= link_to 'Back', climates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Worldgenerator</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zones/_form.html.erb
<%= form_for(@zone) do |f| %>
  <% if @zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
      <% @zone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :visited %><br />
    <%= f.check_box :visited %>
  </div>
  <div class="field">
    <%= f.label :x %><br />
    <%= f.text_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.text_field :y %>
  </div>
  <div class="field">
    <%= f.label :z %><br />
    <%= f.text_field :z %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zones/edit.html.erb
<h1>Editing zone</h1>

<%= render 'form' %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<div id="zones_container" class="index-climates">
<% 
tot=100
@climates.each do |climate| %>
  <%
  v = climate[:default] ? tot : (Math::E**(-(climate[:scale]/10000)*(climate[:distance]**2))*100).floor.to_i
  tot-=v
  (1..v).each do |i| %>
  <div class="index-zone" style="background-color:<%= climate[:color] %>;"><%= climate[:name] %>,<%= i %></div>
  <% 
  end
  end %>
</div>
<table class="index-navigator">
  <tr>
    <td></td>
    <td><%= link_to "North", zone_select_path(@zone.x.to_int,@zone.y.to_int+1,@zone.z.to_int) %></td>
    <td></td>
  </tr>
  <tr>
    <td><%= link_to "West", zone_select_path(@zone.x.to_int-1,@zone.y.to_int,@zone.z.to_int) %></td>
    <td><%= @zone.x.to_int %>, <%= @zone.y.to_int %>, <%= @zone.z.to_int %></td>
    <td><%= link_to "East", zone_select_path(@zone.x.to_int+1,@zone.y.to_int,@zone.z.to_int) %></td>
  </tr>
  <tr>
    <td></td>
    <td><%= link_to "South", zone_select_path(@zone.x.to_int,@zone.y.to_int-1,@zone.z.to_int) %></td>
    <td></td>
  </tr>
</table>
</div>

app/views/zones/map.html.erb
<%
proportions=90;
%>
<div class="map-container">
<div class="map-zone-container" style="width:<%= proportions %>%;height:<%= proportions %>%;top:<%= (100-proportions)/2 %>%;left:<%= (100-proportions)/2 %>%;">
<% cell_size=(((proportions)/@boundaries[:x].to_f)).round(2) %>
  <% @zones.each do |row| %>
          <div class="map-zone" style="width:<%= cell_size %>%;height:<%= cell_size %>%;top:<%= 50-row[:y].to_f*cell_size %>%;left:<%= 50+row[:x].to_f*cell_size %>%;border:1px solid <%= row[:y].to_i == 0 && row[:x].to_i == 0 ? "red" : "black" %>;"><%= link_to row[:id], row, :target => "_blank" %></div>
  <% end %>
</div>
 <% @climates.each do |c| %>
   <div class="map-climate" style="width:<%= c[:radius]*2*cell_size %>%;height:<%= c[:radius]*2*cell_size %>%;top:<%= 50+(-c[:y]-c[:radius])*cell_size %>%; left:<%= 50+(c[:x]-c[:radius])*cell_size %>%;background: -moz-radial-gradient(center, ellipse cover,  <%= c[:color] %> 0%, rgba(8,172,224,1) 1%, rgba(255,255,255,0) 100%);
background: -webkit-gradient(radial, center center, 0px, center center, 100%, color-stop(0%,<%= c[:color] %>),color-stop(100%,rgba(255,255,255,0)));background: -webkit-radial-gradient(center, ellipse cover,  <%= c[:color] %> 0%,rgba(255,255,255,0) 100%);background: -o-radial-gradient(center, ellipse cover,  <%= c[:color] %> 0%,rgba(255,255,255,0) 100%);background: -ms-radial-gradient(center, ellipse cover,  <%= c[:color] %> 0%,rgba(255,255,255,0) 100%);background: radial-gradient(ellipse at center,  <%= c[:color] %> 0%,rgba(255,255,255,0) 100%);filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='<%= c[:color] %>', endColorstr='#00ffffff',GradientType=1 ); border:1px solid <%= c[:color] %>;"><%= c[:name] %></div>
   <% end %>
</div>

app/views/zones/new.html.erb
<h1>New zone</h1>

<%= render 'form' %>

<%= link_to 'Back', map_path %>

app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Visited:</b>
  <%= @zone.visited %>
</p>

<p>
  <b>X:</b>
  <%= @zone.x %>
</p>

<p>
  <b>Y:</b>
  <%= @zone.y %>
</p>

<p>
  <b>Z:</b>
  <%= @zone.z %>
</p>


<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>